#!/usr/bin/env python3
"""Compatibility facade for issue-implementation-loop script helpers."""

from __future__ import annotations

from pathlib import Path
import sys


LIB_DIR = Path(__file__).resolve().parent / "lib"
if str(LIB_DIR) not in sys.path:
    sys.path.insert(0, str(LIB_DIR))

from issue_implementation_loop import (  # noqa: E402
    ACTIVE_STATUSES,
    APPROVED_REVIEW_STATUSES,
    BASE_EFFECTS,
    BASE_POLICY_TYPES,
    COMMIT_RANGE_RE,
    DELIVERY_INTENTS,
    EDGE_STRENGTHS,
    EPIC_RE,
    FINAL_PR_HEADS,
    FINAL_PR_MERGE_POLICIES,
    FULL_SHA_RE,
    ISSUE_PR_BASES,
    ISSUE_PR_MERGE_POLICIES,
    ISSUE_RE,
    MAX_REVIEW_CYCLES,
    RELEASE_ON,
    REMOTE_MODES,
    REVIEWABLE_STATUSES,
    SUCCESS_STATUSES,
    TERMINAL_STATUSES,
    WAITING_STATUSES,
    WORKTREE_STATES,
    ValidationError,
    canonical_issue_branch,
    commit_range_parts,
    compute_next_actions,
    delivery_issue_scope,
    dependency_cycle,
    dependency_satisfied,
    descendants_of,
    dump_json,
    find_skill,
    git_output,
    has_human_risk_acceptance,
    hardening_candidate_registry_path,
    hardening_candidate_report,
    human_blocked_reason,
    is_canonical_issue_branch,
    is_commit_range,
    is_full_commit_sha,
    is_issue_id,
    is_lower_kebab,
    issue_branch_owner,
    issue_record,
    issue_status,
    load_json,
    load_hardening_candidate_registry,
    path_scope_conflicts,
    review_approved_or_accepted,
    scope_conflicts,
    skill_roots,
    validate_delivery_plan,
    validate_execution_envelope,
    validate_input_packet,
    validate_runtime_state,
    validate_worker_report,
)

__all__ = [
    "ACTIVE_STATUSES",
    "APPROVED_REVIEW_STATUSES",
    "BASE_EFFECTS",
    "BASE_POLICY_TYPES",
    "COMMIT_RANGE_RE",
    "DELIVERY_INTENTS",
    "EDGE_STRENGTHS",
    "EPIC_RE",
    "FINAL_PR_HEADS",
    "FINAL_PR_MERGE_POLICIES",
    "FULL_SHA_RE",
    "ISSUE_PR_BASES",
    "ISSUE_PR_MERGE_POLICIES",
    "ISSUE_RE",
    "MAX_REVIEW_CYCLES",
    "RELEASE_ON",
    "REMOTE_MODES",
    "REVIEWABLE_STATUSES",
    "SUCCESS_STATUSES",
    "TERMINAL_STATUSES",
    "WAITING_STATUSES",
    "WORKTREE_STATES",
    "ValidationError",
    "canonical_issue_branch",
    "commit_range_parts",
    "compute_next_actions",
    "delivery_issue_scope",
    "dependency_cycle",
    "dependency_satisfied",
    "descendants_of",
    "dump_json",
    "find_skill",
    "git_output",
    "has_human_risk_acceptance",
    "hardening_candidate_registry_path",
    "hardening_candidate_report",
    "human_blocked_reason",
    "is_canonical_issue_branch",
    "is_commit_range",
    "is_full_commit_sha",
    "is_issue_id",
    "is_lower_kebab",
    "issue_branch_owner",
    "issue_record",
    "issue_status",
    "load_json",
    "load_hardening_candidate_registry",
    "path_scope_conflicts",
    "review_approved_or_accepted",
    "scope_conflicts",
    "skill_roots",
    "validate_delivery_plan",
    "validate_execution_envelope",
    "validate_input_packet",
    "validate_runtime_state",
    "validate_worker_report",
]
